import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {createModel,xy} from './model.js';
import layout from './layout.json';
import {optimize} from './optimize.js';
const embedded=new URLSearchParams(location.search).get('embedded')==='1';
let bookingHandler=null;
const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s),model=createModel(),scene=new THREE.Scene();
if(embedded){document.body.classList.add('embedded');model.tables.forEach(t=>t.status='unavailable')}
scene.background=new THREE.Color('#000000');scene.add(model.root);
const canvas=$('#map');const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;
scene.add(new THREE.HemisphereLight('#fff7e7','#6d7970',1.8));const sun=new THREE.DirectionalLight('#fff1d7',2.6);sun.position.set(-14,35,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40,near:1,far:110});sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;scene.add(sun);scene.add(sun.target);
const fill=new THREE.DirectionalLight('#c4dbe0',.8);fill.position.set(20,15,-25);scene.add(fill);
const camera=new THREE.OrthographicCamera(-25,25,25,-25,.1,250);camera.position.set(-36,48,54);const controls=new OrbitControls(camera,canvas);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.12;controls.minPolarAngle=.08;controls.maxPolarAngle=1.37;controls.minZoom=.65;controls.maxZoom=5;controls.enablePan=true;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};
let currentZone=null,currentTable=null,frame=null,flat=false,step=1,markers=[],pointerStart=null,dirty=true,receipt=null;
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
function resize(){const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(r.width,r.height,false);const a=r.width/r.height,h=Math.max(40,47/a);camera.left=-h*a/2;camera.right=h*a/2;camera.top=h/2;camera.bottom=-h/2;camera.updateProjectionMatrix();dirty=true}new ResizeObserver(resize).observe(canvas.parentElement);
function setStep(n){step=n;document.querySelectorAll('.step').forEach((e,i)=>{e.classList.toggle('active',i+1===n);e.classList.toggle('done',i+1<n)});$('#back').hidden=n===1;$('#back').textContent=n===3?'← Torna al tavolo':'← Tutte le zone';$('#panel').classList.toggle('summary-mode',n===3)}
function animateCamera(target,zoom,resetRotation=false){let offset=camera.position.clone().sub(controls.target);if(resetRotation)offset=new THREE.Vector3(-36,48,54);if(flat)offset=new THREE.Vector3(.01,75,.01);frame={start:performance.now(),from:camera.position.clone(),to:target.clone().add(offset),t0:controls.target.clone(),t1:target.clone(),z0:camera.zoom,z1:zoom};dirty=true}
function paintZones(){for(const z of model.zones){const active=z.id===currentZone;z.overlays.forEach(o=>o.material.opacity=active?.14:0);z.lines.forEach(o=>o.material.opacity=active?1:0)}}
function restoreTable(){for(const t of model.tables)t.group.traverse(o=>{if(o.isMesh&&o.userData.originalMaterial){o.material=o.userData.originalMaterial;delete o.userData.originalMaterial}})}
function highlightTable(t){restoreTable();if(t)t.group.traverse(o=>{if(o.isMesh){o.userData.originalMaterial=o.material;o.material=o.material.clone();o.material.emissive=new THREE.Color('#e10600');o.material.emissiveIntensity=.18}})}
function zoneButton(z){const count=model.tables.filter(t=>t.zoneId===z.id).length;return `<button class="zone-card" data-zone="${z.id}"><span><strong>${z.name}</strong><small>${count} tavoli · disposizione da piantina</small></span><span class="arrow">↗</span></button>`}
function overview(){currentZone=null;currentTable=null;receipt=null;setStep(1);paintZones();restoreTable();$('#panel-title').textContent='Scegli la tua zona.';$('#panel-kicker').textContent='IL CLUB, DA UN ALTRO PUNTO DI VISTA';$('#panel-content').innerHTML=`<p class="intro">Dal palco al giardino: esplora gli spazi e trova il tuo salottino.</p><div class="source-note">Nomi e tavoli dalla tua piantina.<br>Arredi modellati sulle fotografie del Glitz.</div>`;$('#panel-content').querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>chooseZone(b.dataset.zone));$('#sticky-action').hidden=false;$('#action').textContent='Prenota';$('#action').disabled=true;$('#action').onclick=null;$('#action-note').textContent='Seleziona un tavolo sulla mappa';$('#map-caption').textContent='Tocca una zona per esplorarla';rebuildMarkers();animateCamera(new THREE.Vector3(0,0,0),1,true);$('#view-name').textContent='Vista generale';}
function status(t){return {unconfigured:'Da verificare',available:'Disponibile',soldout:'Esaurito',unavailable:'Non disponibile'}[t.status]||'Da verificare'}
function price(t){if(t.priceLabel)return escapeText(t.priceLabel);return Number.isFinite(t.minSpend)?new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(t.minSpend)+' min. tavolo':'Prezzo su richiesta'}
function tableButtons(){return `<div class="table-list">${model.tables.filter(t=>t.zoneId===currentZone).map(t=>`<button data-table="${t.id}" class="table-chip ${t.id===currentTable?'selected':''}" ${['soldout','unavailable'].includes(t.status)?'disabled':''}><i class="dot ${t.status}"></i>${t.id}</button>`).join('')}</div>`}
function bindTableButtons(){document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>chooseTable(b.dataset.table))}
function chooseZone(id,move=true){const z=model.zones.find(z=>z.id===id);if(!z)return;currentZone=id;currentTable=null;receipt=null;setStep(2);paintZones();restoreTable();$('#panel-kicker').textContent='SCEGLI IL TUO SALOTTINO';$('#panel-title').textContent=z.name;$('#panel-content').innerHTML=`<p class="intro">${z.description}</p>${tableButtons()}<div id="table-detail" aria-live="polite"><div class="empty-detail"><span class="selection-icon">◎</span><p>Tocca un indicatore sulla mappa<br>o scegli un ID qui sopra.</p></div></div><div class="source-note">Disposizione e codici dalla piantina fornita. Capienze e condizioni da configurare.</div>`;bindTableButtons();$('#sticky-action').hidden=false;$('#action').textContent='Prenota';$('#action').disabled=true;$('#action').onclick=null;$('#action-note').textContent='Seleziona un tavolo sulla mappa';$('#view-name').textContent=z.name;$('#map-caption').textContent='Seleziona un salottino';rebuildMarkers();if(move){const box=new THREE.Box3().setFromPoints(z.coords.map(p=>xy(...p,z.y)));const target=box.getCenter(new THREE.Vector3());const size=box.getSize(new THREE.Vector3());const viewWidth=camera.right-camera.left,viewHeight=camera.top-camera.bottom;const extent=Math.max(size.x,size.z);animateCamera(target,Math.min(3.2,Math.max(1.4,Math.min(viewWidth,viewHeight)/(extent*1.35))));if(id==='glitzbar'&&!flat)frame.to=target.clone().add(new THREE.Vector3(14,24,14))}}
function chooseTable(id){const t=model.tables.find(t=>t.id===id);if(!t||['soldout','unavailable'].includes(t.status))return;if(currentZone!==t.zoneId||step===3)chooseZone(t.zoneId,false);currentTable=id;setStep(2);highlightTable(t);document.querySelectorAll('[data-table]').forEach(b=>b.classList.toggle('selected',b.dataset.table===id));$('#table-detail').innerHTML=`<div class="table-detail"><div class="row"><span class="eyebrow">IL TUO SALOTTINO</span><span class="status"><i class="dot ${t.status}"></i>${status(t)}</span></div><h3>${t.id}</h3><div class="table-data"><span>Condizioni</span><strong>${price(t)}</strong><span>Ospiti</span><strong>${t.capacity?`Fino a ${t.capacity}`:'Capienza da confermare'}</strong></div></div>`;$('#sticky-action').hidden=false;$('#action').disabled=false;$('#action').textContent='Prenota';$('#action').onclick=()=>{if(bookingHandler){if(t.status==='available')bookingHandler(selection())}else if(!embedded)showSummary()};if(bookingHandler)$('#action').textContent='Prenota';$('#action-note').textContent=bookingHandler?'Apri il modulo · conferma dello staff via WhatsApp':`${model.zones.find(z=>z.id===t.zoneId).name} · ${t.id} · Anteprima`;rebuildMarkers();window.dispatchEvent(new CustomEvent('glitz:table-selected',{detail:selection()}));dirty=true}
function selection(){const t=model.tables.find(t=>t.id===currentTable);return t?{tableId:t.id,zoneId:t.zoneId,zone:model.zones.find(z=>z.id===t.zoneId).name,guests:receipt?.guests??null,minSpend:t.minSpend,currency:'EUR',status:t.status,layoutConfirmedBySource:t.idConfirmedBySource!==false,furnitureDimensionsEstimated:true}:null}
function showSummary(){if(!currentTable)return;const t=model.tables.find(t=>t.id===currentTable);setStep(3);$('#panel-kicker').textContent='LA TUA SCELTA';$('#panel-title').textContent='Una notte al Glitz.';$('#panel-content').innerHTML=`<div class="summary-card"><span class="eyebrow">${model.zones.find(z=>z.id===t.zoneId).name}</span><h3>${t.id}</h3><p>${price(t)}</p></div><label class="field-label" for="guests">QUANTI SIETE?</label><input id="guests" type="number" inputmode="numeric" min="1" ${t.capacity?`max="${t.capacity}"`:''} value="${receipt?.guests||5}" aria-describedby="guest-note"><p class="source-note" id="guest-note">Il numero di ospiti sarà da verificare con la capienza effettiva del tavolo.</p><div class="integration-note"><span>Anteprima della selezione</span><p>Disponibilità, pagamento e conferma non sono ancora collegati al sistema di prenotazione.</p></div>`;$('#action').textContent='Salva la selezione';$('#action').onclick=saveSelection;$('#action-note').textContent='Scarica un riepilogo · nessuna prenotazione';$('#sticky-action').hidden=false;rebuildMarkers()}
function saveSelection(){const input=$('#guests');if(!input.reportValidity())return;receipt={guests:Number(input.value)};const s=selection();download(JSON.stringify(s,null,2),'glitz-selezione.json','application/json');window.dispatchEvent(new CustomEvent('glitz:selection-confirmed',{detail:s}));$('#action-note').textContent='Riepilogo salvato. Nessuna prenotazione effettuata.'}
function download(data,name,type){const blob=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function rebuildMarkers(){syncPlan();const container=$('#markers');container.replaceChildren();markers=[];
for(const t of model.tables.filter(t=>!currentZone||t.zoneId===currentZone)){
const b=document.createElement('button');b.className='table-marker '+t.status+(currentTable===t.id?' selected':'');b.innerHTML=`<i></i><span>${t.id}</span>`;
b.disabled=['soldout','unavailable'].includes(t.status);b.setAttribute('aria-label',`Salottino ${t.id}, ${status(t)}`);b.onclick=()=>chooseTable(t.id);container.append(b);markers.push({el:b,p:t.position})}dirty=true}
let lastMarkerUpdate=0;function updateMarkers(time){if(time-lastMarkerUpdate<25)return;lastMarkerUpdate=time;const r=canvas.getBoundingClientRect();for(const m of markers){const p=m.p.clone().project(camera);m.el.style.transform=`translate(-50%,-100%) translate(${(p.x+1)/2*r.width}px,${(1-p.y)/2*r.height}px)`;m.el.style.visibility=(p.z>1||p.z< -1||Math.abs(p.x)>1.12||Math.abs(p.y)>1.2)?'hidden':'visible'}}
canvas.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY]});canvas.addEventListener('pointerup',e=>{if(!pointerStart||Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1])>6)return;pointerStart=null;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera);if(currentZone){const found=raycaster.intersectObjects(model.pickables.filter(o=>o.userData.zoneId===currentZone))[0];if(found){chooseTable(found.object.userData.tableId);return}}const area=raycaster.intersectObjects(model.hotspots)[0];if(area)chooseZone(area.object.userData.zoneId)});canvas.addEventListener('pointercancel',()=>pointerStart=null);
controls.addEventListener('start',()=>{frame=null});controls.addEventListener('change',()=>dirty=true);
$('#back').onclick=()=>{if(step===3){const t=currentTable;chooseZone(currentZone,false);chooseTable(t)}else overview()};$('#reset').onclick=()=>{flat=false;$('#top').classList.remove('active');overview()};$('#zoom-in').onclick=()=>{camera.zoom=Math.min(5,camera.zoom*1.2);camera.updateProjectionMatrix();dirty=true};$('#zoom-out').onclick=()=>{camera.zoom=Math.max(.65,camera.zoom/1.2);camera.updateProjectionMatrix();dirty=true};$('#top').onclick=()=>{flat=!flat;$('#top').classList.toggle('active',flat);animateCamera(controls.target.clone(),camera.zoom,true)};
$('#arch-view').onclick=()=>{if(!$('#source-plan').hidden)$('#plan-toggle').click();flat=false;$('#top').classList.remove('active');const target=model.arch.root.position.clone().add(new THREE.Vector3(0,2,0));animateCamera(target,3.5,true);frame.to=target.clone().add(new THREE.Vector3(-7,5,18));$('#view-name').textContent='L’arco del Glitz';$('#map-caption').textContent='9 m di larghezza · 5 m sopra la pista';};
$('#help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
function updateInventory(records){if(!Array.isArray(records))throw Error('Inventory must be an array');for(const r of records){const t=model.tables.find(t=>t.id===r.id);if(!t)continue;if(['available','soldout','unavailable','unconfigured'].includes(r.status))t.status=r.status;if(typeof r.priceLabel==='string')t.priceLabel=r.priceLabel;if(r.minSpend===null||Number.isFinite(r.minSpend)&&r.minSpend>=0)t.minSpend=r.minSpend;if(r.capacity===null||Number.isInteger(r.capacity)&&r.capacity>0)t.capacity=r.capacity}const z=currentZone,t=currentTable;if(z){chooseZone(z,false);if(t)chooseTable(t)}else overview();dirty=true}
// Original PDF logo is rendered as geometry by logo.js.
optimize(model);
let planVisible=false;
function syncPlan(){document.querySelectorAll('#plan-hits rect').forEach(r=>{r.classList.toggle('current',r.dataset.id===currentTable);r.style.opacity=currentZone&&r.dataset.zone!==currentZone?.28:1})}
for(const t of layout.filter(t=>Array.isArray(t.schematicPosition))){const r=document.createElementNS('http://www.w3.org/2000/svg','rect');r.setAttribute('x',t.schematicPosition[0]-27);r.setAttribute('y',t.schematicPosition[1]-25);r.setAttribute('width',54);r.setAttribute('height',50);r.setAttribute('rx',3);r.setAttribute('tabindex','0');r.setAttribute('role','button');r.setAttribute('aria-label','Seleziona '+t.id+' sulla piantina');r.dataset.id=t.id;r.dataset.zone=t.zoneId;r.onclick=()=>chooseTable(t.id);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseTable(t.id)}};$('#plan-hits').append(r)}
$('#plan-toggle').onclick=()=>{planVisible=!planVisible;$('#source-plan').hidden=!planVisible;$('.map-stage').classList.toggle('show-plan',planVisible);$('#plan-toggle').classList.toggle('active',planVisible);$('#plan-toggle').textContent=planVisible?'Torna al 3D':'Pianta';syncPlan()};
window.GlitzMap={setBookingHandler:handler=>{bookingHandler=typeof handler==='function'?handler:null;if(currentTable)chooseTable(currentTable)},selectZone:chooseZone,selectTable:chooseTable,reset:overview,getSelection:selection,getTables:()=>model.tables.map(({group,position,...t})=>({...t,position:position.toArray()})),setInventory:updateInventory,exportGLB:async()=>{restoreTable();model.zones.forEach(z=>{z.overlays.forEach(o=>o.visible=false);z.lines.forEach(o=>o.visible=false)});const data=await new GLTFExporter().parseAsync(model.root,{binary:true,onlyVisible:true});model.zones.forEach(z=>{z.overlays.forEach(o=>o.visible=true);z.lines.forEach(o=>o.visible=true)});if(currentTable)highlightTable(model.tables.find(t=>t.id===currentTable));return data},getModelMetadata:()=>model.root.userData};
window.__glitz={model,scene,camera,renderer,controls,get state(){return {step,currentZone,currentTable}},ready:true};
overview();let frames=0;function loop(time){requestAnimationFrame(loop);if(frame){let a=Math.min(1,(time-frame.start)/650),k=1-Math.pow(1-a,3);camera.position.lerpVectors(frame.from,frame.to,k);controls.target.lerpVectors(frame.t0,frame.t1,k);camera.zoom=THREE.MathUtils.lerp(frame.z0,frame.z1,k);camera.updateProjectionMatrix();if(a===1)frame=null;dirty=true}controls.update();if(dirty||frames<5){renderer.render(scene,camera);updateMarkers(time);dirty=false;frames++}}requestAnimationFrame(loop);$('#loading').remove();

