import * as THREE from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export function optimize(model){
 model.root.updateMatrixWorld(true);
 function combine(parent,meshes,tag={}){const inv=parent.matrixWorld.clone().invert(),buckets=new Map();for(const m of meshes){if(Array.isArray(m.material))continue;const key=m.material.uuid;let b=buckets.get(key);if(!b){b={material:m.material,meshes:[]};buckets.set(key,b)}b.meshes.push(m)}
 for(const b of buckets.values()){const gs=[];for(const m of b.meshes){let g=m.geometry.clone();if(g.index)g=g.toNonIndexed();if(!g.attributes.normal)g.computeVertexNormals();if(!g.attributes.uv)g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(g.attributes.position.count*2),2));for(const k of Object.keys(g.attributes))if(!['position','normal','uv'].includes(k))g.deleteAttribute(k);g.applyMatrix4(inv.clone().multiply(m.matrixWorld));gs.push(g)}const geometry=mergeGeometries(gs);if(!geometry)continue;const merged=new THREE.Mesh(geometry,b.material);merged.name=tag.tableId?'TABLE_'+tag.tableId+'_parts':'Architecture_'+b.material.color.getHexString();merged.userData={...tag,components:[...new Set(b.meshes.map(m=>m.name))]};merged.castShadow=true;merged.receiveShadow=true;parent.add(merged);for(const m of b.meshes)m.removeFromParent();for(const g of gs)g.dispose()}}
 const staticMeshes=[];model.root.traverse(o=>{if(o.isMesh&&!o.userData.tableId&&!o.userData.zoneId&&!o.userData.sign&&!o.userData.archComponent)staticMeshes.push(o)});combine(model.root,staticMeshes);
 if(model.arch)for(const group of [model.arch.truss,model.arch.equipment,model.arch.sign,model.arch.rear]){const parts=[];group.traverse(o=>{if(o.isMesh)parts.push(o)});combine(group,parts,{archComponent:true});}
 model.pickables.length=0;for(const t of model.tables){const meshes=[];t.group.traverse(o=>{if(o.isMesh)meshes.push(o)});combine(t.group,meshes,{tableId:t.id,zoneId:t.zoneId});t.group.traverse(o=>{if(o.isMesh)model.pickables.push(o)})}model.root.updateMatrixWorld(true);
}
